all: Juego15

Juego15: Proyecto1-EstructuraDeDatos.o
	g++ -Wall -o Juego15 Proyecto1-EstructuraDeDatos.o
	
Proyecto1-EstructuraDeDatos.o: Proyecto1-EstructuraDeDatos.cpp
	g++ -c -Wall Proyecto1-EstructuraDeDatos.cpp

clean:
	rm *.o Juego15